---
apiVersion: v1
kind: Service
metadata:
  name: {{PROJECT_NAME}}-{{BRANCH_NAME}}
  namespace: {{NAMESPACE}}
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{PROJECT_NAME}}-{{BRANCH_NAME}}
  type: ClusterIP

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{PROJECT_NAME}}-{{BRANCH_NAME}}-virtual-service
  namespace: {{NAMESPACE}}
spec:
  gateways:
  - default/apis-mac-istio-gateway
  hosts:
  - "apis-mac-staging-v2.devcdt.com.br"
  http:
  - match:
    - uri:
        prefix: /{{PREFIX}}/
    rewrite:
      uri: /
    route:
    - destination:
        host: {{PROJECT_NAME}}-{{BRANCH_NAME}}.{{NAMESPACE}}.svc.cluster.local
        port:
          number: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{PROJECT_NAME}}-{{BRANCH_NAME}}
  namespace: {{NAMESPACE}}
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-{{NAMESPACE}}-{{PROJECT_NAME}}-{{BRANCH_NAME}}
  template:
    metadata:
      labels:
        app: {{PROJECT_NAME}}-{{BRANCH_NAME}}
    spec:
      containers:
       - name: {{PROJECT_NAME}}-{{BRANCH_NAME}}
         image: {{IMAGE_URL}}
         readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
         resources:
          requests:
            memory: 50Mi
          limits:
            memory: 450Mi