@NonCPS
def slackNotifier(String buildResult) {
  if ( buildResult == "SUCCESS" ) {
    slackSend ( color: "good",
    teamDomain: 'machina',
    tokenCredentialId: 'machina-slack',
    channel: '#team_ec-build',
    message: "Job: ${env.JOB_NAME} \nBuild: ${env.BUILD_NUMBER} \nStatus: Sucesso \nTempo: ${currentBuild.durationString.minus(' and counting')}")
  }
  else if( buildResult == "FAILURE" ) {
    slackSend( color: "danger",
    teamDomain: 'machina',
    tokenCredentialId: 'machina-slack',
    channel: '#team_ec-build',
    message: "Job: ${env.JOB_NAME} \nBuild: ${env.BUILD_NUMBER} \nStatus: Falha \nTempo: ${currentBuild.durationString.minus(' and counting')}")
  }
  else if( buildResult == "UNSTABLE" ) {
    slackSend( color: "warning",
      teamDomain: 'machina',
      tokenCredentialId: 'machina-slack',
      channel: '#team_ec-build',
      message: "Job: ${env.JOB_NAME} \nBuild: ${env.BUILD_NUMBER} \nStatus: Unstable \nTempo: ${currentBuild.durationString.minus(' and counting')}")
  }
  else if( buildResult == "ABORTED" ) {
    slackSend( teamDomain: 'machina',
      tokenCredentialId: 'machina-slack',
      channel: '#team_ec-build',
      message: "Job: ${env.JOB_NAME} \nBuild: ${env.BUILD_NUMBER} \nStatus: Abortado \nTempo: ${currentBuild.durationString.minus(' and counting')}")
  }
  else if( buildResult == "null" ) {
    slackSend( color: "warning",
      teamDomain: 'machina',
      tokenCredentialId: 'machina-slack',
      channel: '#team_ec-build',
      message: "Job: ${env.JOB_NAME} \nBuild: ${env.BUILD_NUMBER} \nStatus: Desconhecido \nTempo: ${currentBuild.durationString.minus(' and counting')}")
  }
}

@NonCPS
def configFromBranch(branch) {
    def env_dev = [
        rancherContext: 'c-lh4tc:p-bcs6n',
        deploymentFile: 'deployment.yml',
        namespace: 'ec-qa'
    ]    
    def env_qa = [
        rancherContext: 'c-lh4tc:p-bcs6n',
        deploymentFile: 'deployment.yml',
        namespace: 'ec-qa'
    ]
    def env_staging = [
        rancherContext: 'c-lh4tc:p-bcs6n',
        deploymentFile: 'deployment.yml',
        namespace: 'ec-staging'
    ]
    def env_prd = [
        rancherContext: 'c-xsmcp:p-wjhpx',
        deploymentFile: 'deployment.yml',
        namespace: 'ec'
    ]
    if (branch ==~ /(develop)/) { 
        return [
            shouldTest: true,
            shouldAnalyze: true,
            shouldBuildImage: true,
            shouldPushImage: true,
            shouldDeploy: true,
            nexusUpload: true,
            rancherCred: 'rancher2-machina-qa-token',
            rancherURL: 'rancher2-machina-qa-url',
            env: 'develop',
            tag: 'dev',
            deployments: [env_dev]
        ]
    }    
    if (branch ==~ /(qa)/) { 
        return [
            shouldTest: true,
            shouldAnalyze: true,
            shouldBuildImage: true,
            shouldPushImage: true,
            shouldDeploy: true,
            nexusUpload: true,
            rancherCred: 'rancher2-machina-qa-token',
            rancherURL: 'rancher2-machina-qa-url',
            env: 'qa',
            tag: 'qa',
            deployments: [env_qa]
        ]
    }
    
    
    else if (branch ==~ /(staging)/) {
        return [
            shouldTest: true,
            shouldAnalyze: true,
            shouldBuildImage: true,
            shouldPushImage: true,
            shouldDeploy: true,
            nexusUpload: true,
            rancherCred: 'rancher2-machina-qa-token',
            rancherURL: 'rancher2-machina-qa-url',
            env: 'staging',
            tag: 'stg',
            deployments: [env_staging]
        ]
    }
    else if (branch ==~ /(master)/) {
        return [
            shouldTest: true,
            shouldAnalyze: true,
            shouldBuildImage: true,
            shouldPushImage: true,
            shouldDeploy: true,
            nexusUpload: true,
            rancherCred: 'rancher2-machina-qa-token',
            rancherURL: 'rancher2-machina-qa-url',
            env: 'production',
            tag: 'prd',
            deployments: [env_prd]
        ]
    }
    else {
        return [
            shouldTest: false,
            shouldAnalyze: false,
            shouldBuildImage: false,
            shouldPushImage: false,
            shouldDeploy: false,
            nexusUpload: false,
            rancherCred: 'rancher2-machina-qa-token',
            rancherURL: 'rancher2-machina-qa-url',
            tag: '-',
            deployments: []
        ]
    }
}

pipeline {
    agent none
    
    environment {
        CONFIG = configFromBranch(BRANCH_NAME)
        SHOULD_TEST = "${CONFIG.shouldTest}"
        SHOULD_ANALYZE = "${CONFIG.shouldAnalyze}"
        SHOULD_BUILD_IMAGE = "${CONFIG.shouldBuildImage}"
        SHOULD_PUSH_IMAGE = "${CONFIG.shouldPushImage}"
        SHOULD_DEPLOY = "${CONFIG.shouldDeploy}"
        NEXUS_UPLOAD = "${CONFIG.nexusUpload}"
        JAR_SUFFIX = "${CONFIG.jarSuffix}"
        ENV = "${CONFIG.env}"
        TAG = "${CONFIG.tag}"
        NAME ="${CONFIG.namespace}"

        RANCHER_CRED = "${CONFIG.rancherCred}"
        RANCHER_URL = "${CONFIG.rancherURL}"

        PROJECT_NAME="est-wrk-autoec-lead"
        GIT_URL="git@bitbucket.org:machina/${PROJECT_NAME}.git"

        IMAGE_URL = "123721783999.dkr.ecr.sa-east-1.amazonaws.com/${PROJECT_NAME}"
    }
          
    stages {
        stage ('CI') {
            agent {
                label 'TestContainer'
            }
            stages {
                stage('SCM - Checkout') {
                    steps{
                        cleanWs()
                        git branch: BRANCH_NAME,
                        credentialsId: "bitb-machina",
                        url: GIT_URL
                        echo 'SCM Checkout'
                    }
                }
                stage ('Tests'){
                    when {
                        expression { SHOULD_TEST == 'true' }
                    }
                    stages {
                        stage('Integration Tests - Gradle'){
                            steps {
                                sh "chmod +x gradlew"
                                sh "./gradlew -i clean test jacocoTestReport jacocoTestCoverageVerification --stacktrace"
                            }
                        }
                        stage('Code coverage - Jacoco'){
                            steps{
                                jacoco(
                                    execPattern: 'target/*.exec',
                                    classPattern: 'target/classes',
                                    sourcePattern: 'src/main/java',
                                    exclusionPattern: 'src/test*'
                                )
                            }
                        }
                    }
                }
                stage ('SonarQube & Quality Gate'){
                    when {
                        expression { SHOULD_ANALYZE == 'true' }
                    }
                    stages{
                        stage('Analysis - SonarQube'){
                            steps {
                                withSonarQubeEnv('SONAR'){
                                    sh "./gradlew -i sonarqube --stacktrace \
                                    -Dsonar.projectKey=${PROJECT_NAME}-${BRANCH_NAME} \
                                    -Dsonar.projectName=${PROJECT_NAME}-${BRANCH_NAME}"
                                }
                            }
                        }
                        stage('Quality gate'){
                            steps {
                                timeout ( time: 1, unit: 'HOURS'){
                                    script{
                                        def qg = waitForQualityGate()
                                        if (qg.status != 'OK'){
                                            error "Pipeline aborted due to a quality gate failure: ${qg.status}"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        stage ('CD') {
            stages {
                stage ('Deploy') {
                    agent {
                        label 'Build'
                    }
                    tools {
                        jdk 'jdk11-open'
                    }
                    stages{                       
                        stage ('Build Application'){
                            steps{
                                sh "chmod +x gradlew"
                                sh "./gradlew -i bootJar"
                            }
                        }
                        stage ('Docker - Build') {
                            when {
                              expression { SHOULD_BUILD_IMAGE == 'true' }
                            }                  
                            steps {
                                script{
                                    VERSION = sh(script: './gradlew properties --no-daemon --console=plain -q | grep "^version:" | awk \'{printf $2}\' | xargs', , returnStdout: true).trim()
                                    IMAGE = "${IMAGE_URL}:${TAG}-${VERSION}"
                                }
                                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'machina-ecr', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY']]) {
                                    sh "export AWS_DEFAULT_REGION=sa-east-1"
                                    sh "\$(/usr/local/bin/aws ecr get-login --no-include-email --region sa-east-1)"
                                    sh "docker build --pull -t ${IMAGE} --no-cache ."
                                }
                            }
                        }
                        stage('Docker - Push'){
                            when {
                              expression { SHOULD_PUSH_IMAGE == 'true' }
                            }
                            steps{
                                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'machina-ecr', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY']]) {
                                    sh "docker push ${IMAGE}"
                                    echo "Image push complete"
                                }
                            }
                        }
                        stage('Sysdig Analysis - Scan'){
                            when {
                              expression { SHOULD_PUSH_IMAGE == 'true' }
                            }
                            steps{
                                sh "echo ${IMAGE} > sysdig_secure_images"
                                sysdig engineCredentialsId: 'sysdig-token', name: 'sysdig_secure_images', inlineScanning: true, bailOnFail: false, bailOnPluginFail: false
                            }
                        }
                        stage('Rancher - Deploy'){
                            when {
                              expression { SHOULD_DEPLOY == 'true' }
                            }
                            steps {
                                script { 
                                    for (deployment in configFromBranch(BRANCH_NAME).deployments) {
                                        withCredentials([
                                            string(credentialsId: "${RANCHER_CRED}", variable: 'rancherToken'),
                                            string(credentialsId: "${RANCHER_URL}", variable: 'rancherURL')
                                            ]){
                                                sh "echo yes | /usr/bin/rancher login --token token-some-token  --context ${deployment.rancherContext} --name rancher2 https://ec2-18-228-89-100.sa-east-1.compute.amazonaws.com/v3"
	                                            //sh "echo yes | /usr/bin/rancher login --token ${rancherToken} --context ${deployment.rancherContext} --name rancher2 ${rancherURL}" 
                                            }  
                                                sh """
                                                sed '
                                                  s,{{IMAGE_URL}},${IMAGE},g;
                                                  s,{{NAMESPACE}},${deployment.namespace},g;
                                                  s,{{PROJECT_NAME}},${PROJECT_NAME},g;
                                                ' ${deployment.deploymentFile} | /usr/bin/rancher kubectl apply -f -
                                                """
                                    }
                                }
                             }
                         }
                    }
                }
            }
        }
    }
    post {
        success {
            script{
                slackNotifier('SUCCESS')
            }
        }
        failure{
            script{
                slackNotifier('FAILURE')
            }
        }
        unstable{
            script{
                slackNotifier('UNSTABLE')
            }
        }
        aborted{
            script{
                slackNotifier('ABORTED')
            }
        }
    }
}
