export const Routes = {
  ACCESS_PERMISSION: "RhFront.AccessPermission",
  FIRST_ACCESS: "RhFront.FirstAccess",
  CREATE_PASSWORD: "RhFront.CreatePassword",
  CREATED_PASSWORD: "RhFront.CreatedPassword",
  LOGIN: "RhFront.Login",
  FORGOTPASSWORD: "RhFront.ForgotPassword",
  USERS_REGISTRY: "RhFront.UsersRegistry",
  USERS_REGISTRY_EDIT: "RhFront.UsersRegistryEdit",
  ORDER_DETAILS: "RhFront.OrderDetails",
  EMPLOYEE_STATEMENT: "RhFront.EmployeeStatement",
  EMPLOYEES: "RhFront.Employees",
  REPORTS: "RhFront.Reports",
  FINANCES: "RhFront.Finances",
  MY_PAYMENTS: "RhFront.MyPayments",
  INCOME_REPORT: "RhFront.IncomeReport",
  VIRTUAL_ACCOUNT: "RhFront.VirtualAccount",
  ORDERS_DASHBOARD: "RhFront.OrdersDashboard",
  ORDER_CONFIRMATION: "RhFront.OrderConfirmation",
  CARD_TRACKING: "RhFront.CardTracking",
  NEW_ORDER: "RhFront.OrderNew",
  ORDER_ERRORS: "RhFront.OrderErrors",
  USER_DETAILS: "RhFront.UserDetails",
  ORDER_DETAILS_BY_COMPANY: "RhFront.UserDetailsByCompany",
  DELIVERY_PLACES: "RhFront.DeliveryPlaces",
  DELIVERY_PLACES_NEW: "RhFront.DeliveryPlacesNew",
  DELIVERY_PLACES_NEW_MANUALLY: "RhFront.DeliveryPlacesNewManually",
  DELIVERY_PLACES_EDIT_MANUALLY: "RhFront.DeliveryPlacesEditManually",
  DELIVERY_PLACES_SUCCESS: "RhFront.DeliveryPlacesSuccess",
  DELIVERY_PLACES_ERRORS: "RhFront.DeliveryPlacesErrors",
  FILE_CONVERTER: "RhFront.FileConverter",
  TERM_PRIVACY: "RhFront.TermPrivacy",
  UPDATE_USER: "RhFront.UpdateUser",
};

export const WebPaths = {
  [Routes.ACCESS_PERMISSION]: "/permissao-accesso",
  [Routes.FIRST_ACCESS]: "/primeiro-acesso",
  [Routes.CREATE_PASSWORD]: "/criar-senha",
  [Routes.CREATED_PASSWORD]: "/senha-criada",
  [Routes.LOGIN]: "/login",
  [Routes.FORGOTPASSWORD]: "/recuperar-senha",
  [Routes.USERS_REGISTRY]: "/cadastrar-usuario",
  [Routes.USERS_REGISTRY_EDIT]: "/editar-usuario/:userId",
  [Routes.FINANCES]: "/financeiro",
  [Routes.MY_PAYMENTS]: "/financeiro/meus-pagamentos",
  [Routes.INCOME_REPORT]: "/financeiro/informe-rendimentos",
  [Routes.VIRTUAL_ACCOUNT]: "/financeiro/conta-virtual",
  [Routes.EMPLOYEE_STATEMENT]:
    "/funcionarios/extrato-funcionario/:employeeCPF?",
  [Routes.EMPLOYEES]: "/funcionarios",
  [Routes.REPORTS]: "/relatorios",
  [Routes.CARD_TRACKING]: "/funcionarios/rastreio-cartao",
  [Routes.ORDERS_DASHBOARD]: "/pedidos",
  [Routes.ORDER_CONFIRMATION]: "/confirmar-pedido/:orderId",
  [Routes.ORDER_DETAILS]: "/pedidos/detalhes/:orderId?",
  [Routes.NEW_ORDER]: "/pedidos/novo",
  [Routes.ORDER_ERRORS]: "/pedidos/erros/:fileId?",
  [Routes.USER_DETAILS]: "/usuarios/detalhes/:matrixId?",
  [Routes.ORDER_DETAILS_BY_COMPANY]: "/pedidos/detalhes/:orderId?/:chargeId?",
  [Routes.DELIVERY_PLACES]: "/locais-entrega",
  [Routes.DELIVERY_PLACES_NEW]: "/locais-entrega/novo",
  [Routes.DELIVERY_PLACES_NEW_MANUALLY]: "/locais-entrega/cadastrar-local",
  [Routes.DELIVERY_PLACES_EDIT_MANUALLY]:
    "/locais-entrega/editar-local/:deliveryPlaceId",
  [Routes.DELIVERY_PLACES_SUCCESS]: "/locais-entrega/sucesso",
  [Routes.DELIVERY_PLACES_ERRORS]: "/locais-entrega/erros/:fileId?",
  [Routes.REPORTS]: "/relatorios",
  [Routes.FILE_CONVERTER]: "/conversor",
  [Routes.TERM_PRIVACY]: "/termo-privacidade",
  [Routes.UPDATE_USER]: "/atualizar-usuario",
  [Routes.DEFAULT]: "/",
};

export const NAVIGATION_TYPE = {
  PUSH: "push",
  BACK: "back",
};
