// id -> código da uf
// name -> uf
export default [
  { id: 12, name: "AC" },
  { id: 27, name: "AL" },
  { id: 13, name: "AM" },
  { id: 16, name: "AP" },
  { id: 29, name: "BA" },
  { id: 23, name: "CE" },
  { id: 53, name: "DF" },
  { id: 32, name: "ES" },
  { id: 52, name: "GO" },
  { id: 21, name: "MA" },
  { id: 31, name: "MG" },
  { id: 50, name: "MS" },
  { id: 51, name: "MT" },
  { id: 15, name: "PA" },
  { id: 25, name: "PB" },
  { id: 26, name: "PE" },
  { id: 22, name: "PI" },
  { id: 41, name: "PR" },
  { id: 33, name: "RJ" },
  { id: 24, name: "RN" },
  { id: 11, name: "RO" },
  { id: 14, name: "RR" },
  { id: 43, name: "RS" },
  { id: 42, name: "SC" },
  { id: 28, name: "SE" },
  { id: 35, name: "SP" },
  { id: 17, name: "TO" },
];
