@NonCPS
def slackNotifier(String buildResult) {
  if ( buildResult == "SUCCESS" ) {
    slackSend ( color: "good",
    teamDomain: 'macmaceficios',
    tokenCredentialId: 'mac-slack',
    channel: '#financeiro_contabil-build',
    message: "Job: ${env.JOB_NAME} \nBuild: ${env.BUILD_NUMBER} \nStatus: Sucesso \nTempo: ${currentBuild.durationString.minus(' and counting')}")
  }
  else if( buildResult == "FAILURE" ) {
    slackSend( color: "danger",
    teamDomain: 'macmaceficios',
    tokenCredentialId: 'mac-slack',
    channel: '#financeiro_contabil-build',
    message: "Job: ${env.JOB_NAME} \nBuild: ${env.BUILD_NUMBER} \nStatus: Falha \nTempo: ${currentBuild.durationString.minus(' and counting')}")
  }
  else if( buildResult == "UNSTABLE" ) {
    slackSend( color: "warning",
      teamDomain: 'macmaceficios',
      tokenCredentialId: 'mac-slack',
      channel: '#financeiro_contabil-build',
      message: "Job: ${env.JOB_NAME} \nBuild: ${env.BUILD_NUMBER} \nStatus: Unstable \nTempo: ${currentBuild.durationString.minus(' and counting')}")
  }
  else if( buildResult == "ABORTED" ) {
    slackSend( teamDomain: 'macmaceficios',
      tokenCredentialId: 'mac-slack',
      channel: '#financeiro_contabil-build',
      message: "Job: ${env.JOB_NAME} \nBuild: ${env.BUILD_NUMBER} \nStatus: Abortado \nTempo: ${currentBuild.durationString.minus(' and counting')}")
  }
  else if( buildResult == "null" ) {
    slackSend( color: "warning",
      teamDomain: 'macmaceficios',
      tokenCredentialId: 'mac-slack',
      channel: '#financeiro_contabil-build',
      message: "Job: ${env.JOB_NAME} \nBuild: ${env.BUILD_NUMBER} \nStatus: Desconhecido \nTempo: ${currentBuild.durationString.minus(' and counting')}")
  }
}

def startMsg() {
  commit_desc = sh(script: "git log -1 --format='format:%s'", returnStdout: true).trim()
  slackSend(teamDomain: 'macmaceficios',
    tokenCredentialId: 'mac-slack',
    channel: '#financeiro_contabil-build',
    message: "Job: ${env.JOB_NAME} \nBuild: <${env.BUILD_URL}|build ${env.BUILD_DISPLAY_NAME}> \nIniciado por: ${env.BUILD_USER}\n Commit: ${commit_desc}\nBranch: ${env.BRANCH_NAME}")
}
@NonCPS
def configFromBranch(branch) {
    def env_dev = [
        deploymentFile: 'deployment.yml',
        namespace: 'financeiro-contabil-dev'
    ]
    def env_staging = [
        deploymentFile: 'deployment.yml',
        namespace: 'financeiro-contabil-staging'
    ]
    def env_prd = [
        deploymentFile: 'deployment.yml',
        namespace: ''
    ]
    if (branch ==~ /(develop)/) { 
        return [
            shouldTest: false,
            shouldAnalyze: false,
            shouldBuildImage: false,
            shouldPushImage: false,
            shouldDeploy: false,
            kubeconfig: "config-eks-dev",
            jarSuffix: '-SNAPSHOT',
            env: 'develop',
            tag: 'dev',
            deployments: [env_dev]
        ]
    }
    else if (branch ==~ /(migracao)/) {
        return [
            shouldTest: false,
            shouldAnalyze: false,
            shouldBuildImage: true,
            shouldPushImage: true,
            shouldDeploy: true,
            kubeconfig: "config-eks-dev",
            env: 'staging',
            tag: 'stg',
            deployments: [env_staging]
        ]
    }
    else if (branch ==~ /(staging)/) {
        return [
            shouldTest: false,
            shouldAnalyze: false,
            shouldBuildImage: true,
            shouldPushImage: true,
            shouldDeploy: true,
            kubeconfig: "config-eks-dev",
            jarSuffix: '-RC',
            env: 'staging',
            tag: 'stg',
            deployments: [env_staging]
        ]
    }
    else if (branch ==~ /(master)/) {
        return [
            shouldTest: false,
            shouldAnalyze: false,
            shouldBuildImage: true,
            shouldPushImage: true,
            shouldDeploy: false,
            kubeconfig: "",
            jarSuffix: '',
            env: 'production',
            tag: 'prd',
            deployments: [env_prd]
        ]
    }
    else {
        return [
            shouldTest: false,
            shouldAnalyze: false,
            shouldBuildImage: false,
            shouldPushImage: false,
            shouldDeploy: false,
            kubeconfig: "config-eks-dev",
            jarSuffix: "dft",
            tag: 'dft',
            deployments: []
        ]
    }
}

pipeline {
    agent none
    
    environment {
        CONFIG = configFromBranch(BRANCH_NAME)
        SHOULD_TEST = "${CONFIG.shouldTest}"
        SHOULD_ANALYZE = "${CONFIG.shouldAnalyze}"
        SHOULD_BUILD_IMAGE = "${CONFIG.shouldBuildImage}"
        SHOULD_PUSH_IMAGE = "${CONFIG.shouldPushImage}"
        SHOULD_DEPLOY = "${CONFIG.shouldDeploy}"
        NEXUS_UPLOAD = "${CONFIG.nexusUpload}"
        JAR_SUFFIX = "${CONFIG.jarSuffix}"
        ENV = "${CONFIG.env}"
        NAME ="${CONFIG.namespace}"
        TAG = "${CONFIG.tag}"
        KUBECONFIG = "${CONFIG.kubeconfig}"

        GIT_URL="git@bitbucket.org:maquiinaedu/ctb-wkr-atutransac.git"
        PROJECT_NAME="ctb-wkr-atutransac"

        IMAGE_TAG = "${CONFIG.tag}-${env.BUILD_ID}"
        IMAGE_NAME = "${PROJECT_NAME}:${IMAGE_TAG}"
        IMAGE_URL = "123721783999.dkr.ecr.sa-east-1.amazonaws.com/${IMAGE_NAME}"
    }
          
    stages {
        stage ('CI') {
            agent {
                label 'TestContainer'
            }
            stages {
                stage('SCM - Checkout') {
                    steps{
                        cleanWs()
                        git branch: BRANCH_NAME,
                        credentialsId: "bitb-mac",
                        url: GIT_URL
                        echo 'SCM Checkout'
                    }
                }
                stage ('Tests'){
                    when {
                        expression { SHOULD_TEST == 'true' }
                    }
                    stages {
                        stage('Integration Tests - Gradle'){
                            steps {
                                sh "./gradlew -i clean test jacocoTestReport jacocoTestCoverageVerification --stacktrace"
                            }
                        }
                        stage('Code coverage - Jacoco'){
                            steps{
                                jacoco(
                                    execPattern: 'target/*.exec',
                                    classPattern: 'target/classes',
                                    sourcePattern: 'src/main/java',
                                    exclusionPattern: 'src/test*'
                                )
                            }
                        }
                    }
                }
                stage ('SonarQube & Quality Gate'){
                    when {
                        expression { SHOULD_ANALYZE == 'true' }
                    }
                    stages{
                        stage('Analysis - SonarQube'){
                            steps {
                                withSonarQubeEnv('SONAR'){
                                    sh "./gradlew -i sonarqube --stacktrace \
                                    -Dsonar.projectKey=${PROJECT_NAME}-${BRANCH_NAME} \
                                    -Dsonar.projectName=${PROJECT_NAME}-${BRANCH_NAME}"
                                }
                            }
                        }
                        stage('Quality gate'){
                            steps {
                                timeout ( time: 1, unit: 'HOURS'){
                                    script{
                                        def qg = waitForQualityGate()
                                        if (qg.status != 'OK'){
                                            error "Pipeline aborted due to a quality gate failure: ${qg.status}"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        stage ('CD') {
            
            stages {
                stage ('Deploy') {
                    agent {
                        label 'Build'
                    }
                    stages{                       
                        stage ('Build Application'){
                            steps{
                             sh "./gradlew -i assemble"
                            }
                        }  
                        stage ('Nexus upload'){
                            when {
                              expression { NEXUS_UPLOAD == 'true'} 
                            }
                            steps{

                                sh "./gradlew -i uploadArchives"

                            }
                        }                                                                               
                        stage ('Docker - Build') {
                            when {
                              expression { SHOULD_BUILD_IMAGE == 'true' }
                            }
                            steps {
                                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'mac-ecr', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY']]) {
                                    sh "export AWS_DEFAULT_REGION=sa-east-1"
                                    sh "\$(/usr/local/bin/aws ecr get-login --no-include-email --region sa-east-1)"
                                    sh "docker build --pull -t ${IMAGE_URL} --no-cache ."
                                }
                            }
                        }
                        stage('Push Image - Docker'){
                            when {
                              expression { SHOULD_PUSH_IMAGE == 'true' }
                            }
                            steps{
                                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'mac-ecr', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY']]) {
                                    sh "docker push ${IMAGE_URL}"
                                    echo "Image push complete"
                                }
                            }
                        }
                        stage('Sysdig Analysis - Scan'){
                            when {
                              expression { SHOULD_PUSH_IMAGE == 'true' }
                            }
                            steps{
                                sh "echo ${IMAGE_URL} > sysdig_secure_images"
                                script {
                                    try {
                                        sysdig engineCredentialsId: 'sysdig-token', name: 'sysdig_secure_images', inlineScanning: true, bailOnFail: false, bailOnPluginFail: true
                                    } catch (err) {
                                        echo err.getMessage()
                                        COMMIT_AUTHOR_EMAIL= sh(script: "git log -1 --pretty=format:\"%ae\"", , returnStdout: true).trim()
                                        wrap([$class: 'BuildUser']) {
                                            mail body: "Atenção, o job ${env.JOB_NAME} não passou na análise do Sysdig. Para mais informações, consulte o link abaixo.\
                                                        \n\nLink do build: ${BUILD_URL}", 
                                                         from: 'jenkins@macpreprod.com', 
                                                         mimeType: 'text/plain', 
                                                         replyTo: 'no-reply@macpreprod.com', 
                                                         subject: 'Falha no Sysdig', 
                                                         to: "${COMMIT_AUTHOR_EMAIL}"
                                        }
                                        sh "exit 1"
                                    }
                                }
                            }
                        }
                        stage('EKS - Deploy'){
                            when {
                              expression { SHOULD_DEPLOY == 'true' }
                            }
                            steps {
                                script {
                                    for (deployment in configFromBranch(BRANCH_NAME).deployments) {
                                        withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'mac-qa-aws', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY']]) {
                                            sh """
                                                export AWS_DEFAULT_REGION=us-east-2
                                                """
                                            sh """
                                                sed '
                                                  s,{{IMAGE_URL}}, ${IMAGE_URL},g;
                                                  s,{{NAMESPACE}},${deployment.namespace},g;
                                                  s,{{PROJECT_NAME}},${PROJECT_NAME},g;
                                                  s,{{TAG}},${TAG},g;
                                                ' ${deployment.deploymentFile} | kubectl apply --kubeconfig /home/jenkins/.kube/${KUBECONFIG} -f -
                                                """ 
                                        }      
                                        
                                    }   
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    post {
        success {
            script{
                slackNotifier('SUCCESS')
            }
        }
        failure{
            script{
                slackNotifier('FAILURE')
            }
        }
        unstable{
            script{
                slackNotifier('UNSTABLE')
            }
        }
        aborted{
            script{
                slackNotifier('ABORTED')
            }
        }
    }
}