ENV USER=appuser
ENV UID=16000
ENV GID=16001

RUN mkdir -p app/trace  && \
    addgroup -g $GID $USER && \
    adduser --disabled-password --gecos "" --home /app --ingroup $USER --no-create-home --uid $UID $USER && \
    chown $USER:$USER -R /app 

WORKDIR /app

COPY --chown=appuser:appuser ./target/*.jar ./app.jar

USER appuser

ENTRYPOINT ["java", "-jar", "app.jar"]
