FROM 123721783999.dkr.ecr.sa-east-1.amazonaws.com/maquiinaedu:nginx-alpine

WORKDIR /usr/share/nginx/html/

COPY ./dist/ /usr/share/nginx/html/

# RUN mkdir ./assets &&  mv *.png *.svg assets/

RUN ls -lhtr .
